=== Fallest/1-DAM/LM/XML/Schemas/Ejercicio8/ejercicio8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="pedido">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="destino" type="TipoDireccion"/>
        <xs:element name="ordenante" type="TipoDireccion"/>
        <xs:element name="observaciones" type="xs:string" minOccurs="0"/>
        <xs:element name="contenido">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="producto" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="cantidad" type="xs:integer"/>
                    <xs:element name="precio" type="xs:decimal"/>
                    <xs:element name="observaciones" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="fecha" type="xs:date" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="TipoDireccion">
    <xs:sequence>
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="direccion" type="xs:string"/>
    <xs:element name="ciudad" type="xs:string"/>
    <xs:element name="codpostal">
      <xs:simpleType>
        <xs:restriction base="xs:positiveInteger">
          <xs:minInclusive value="1000"/>
          <xs:maxInclusive value="60000"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Fallest/1-DAM/LM/XML/Schemas/Ejercicio8/Ejercicio8.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedido fecha="2020-08-20" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/David/Documents/1%C2%BA%20DAM/LM/XML/Schemas/Ejercicio8/ejercicio8.xsd">
  <destino>
    <nombre>María</nombre>
    <direccion>Alcalá de Guadaíra</direccion>
    <ciudad>Sevila</ciudad>
    <codpostal>41006</codpostal>
  </destino>
  <ordenante>
    <nombre>Manuel</nombre>
    <direccion>Santiponce</direccion>
    <ciudad>Sevilla</ciudad>
    <codpostal>40909</codpostal>  
  </ordenante>
  <observaciones/>
  <contenido>
    <producto>
      <nombre>NVidia GeForce GTX 1050 Ti 4GB DRAM GDDR5</nombre>
      <cantidad>1</cantidad>
      <precio>421.23</precio>
      <observaciones>Cuidado, Frágil</observaciones>
    </producto>
  </contenido>
</pedido>
